### ISSUE TITLE
请求出现 WARNING:  Invalid HTTP request received. 错误

### ISSUE THREAD

**Issue by ProgrammerHuang** [vtuber-plan/olah#33]
我是用Docker容器里跑olah, 外面再用Nginx做反向代理转到olah上, Python 3.12.

运行的命令是:
olah-cli --host 0.0.0.0 --port 8090 --mirror-netloc hf-mirror.mytest.com

但每次请求进来都是报下面的警告:
WARNING:  Invalid HTTP request received.

并返回错误.

我这样部署是不是需要注意什么? 有哪里需要特别配置的?

**Comment by jstzwj** [comment]
确认一下，启用的HTTP和HTTPS协议和客户端请求的协议是否一致
